### ISSUE TITLE
Error when installing on macOS

### ISSUE THREAD

**Issue by seannymurrs** [hfreire/pollmommy#1010]
I'm getting the following error when trying to install on my M1 MacBook mini. I'm assuming it's due to it being an M1-based system, but I'm not sure how to proceed from here.

```
1057 error code 1
1058 error path /opt/homebrew/lib/node_modules/pollmommy/node_modules/electron
1059 error command failed
1060 error command sh -c node install.js
1061 error Downloading electron-v2.0.18-darwin-arm64.zip
1061 error [>                                            ] 0.0% (0 B/s)
1061 error [1000D[0K[1A[1000D[0K[1A[1000D[0KDownloading electron-v2.0.18-darwin-arm64.zip
1061 error Error: GET https://github.com/electron/electron/releases/download/v2.0.18/electron-v2.0.18-darwin-arm64.zip returned 404
1062 error /opt/homebrew/lib/node_modules/pollmommy/node_modules/electron/install.js:54
1062 error   throw err
1062 error   ^
1062 error
1062 error Error: Failed to find Electron v2.0.18 for darwin-arm64 at https://github.com/electron/electron/releases/download/v2.0.18/electron-v2.0.18-darwin-arm64.zip
1062 error     at Request.<anonymous> (/opt/homebrew/lib/node_modules/pollmommy/node_modules/nugget/index.js:169:61)
1062 error     at Request.emit (node:events:390:28)
1062 error     at Request.onRequestResponse (/opt/homebrew/lib/node_modules/pollmommy/node_modules/request/request.js:1059:10)
1062 error     at ClientRequest.emit (node:events:390:28)
1062 error     at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:623:27)
1062 error     at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)
1062 error     at TLSSocket.socketOnData (node:_http_client:487:22)
1062 error     at TLSSocket.emit (node:events:390:28)
1062 error     at addChunk (node:internal/streams/readable:324:12)
1062 error     at readableAddChunk (node:internal/streams/readable:297:9)
1062 error
1062 error Node.js v17.0.1
1063 verbose exit 1
```

**Comment by vascobarbosa** [comment]
+1
